title = "instance templates"

[settings]
# what happens when a file with the same name is already there
default_behavior = "fail"

[templates.nix-default-file]
path = "./default.nix"
call_name = "nix.default"

[templates.nix-shell-file]
path = "./shell.nix"
call_name = "nix.shell"

[templates.nix-rust-file]
rename = "shell.nix"
path = "./rust.dev.shell.nix"
call_name = "nix.lang.rust.dev"

[templates.readme-file]
rename = "README.md"
path = "./README.md"
call_name = "md.readme"

[templates.ignore-targets-cargo]
rename = ".gitignore"
path = "./cargo-defaults.gitignore"
call_name = "gitignore.cargo"
behavior = "append"
